Reddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts
end

Reddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Reddit/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
   
  belongs_to :author, 
    foreign_key: :author_id,
    class_name: :User
    
  has_many :postsubs,
  foreign_key: :post_id,
  class_name: :Postsub,
  dependent: :destroy,
  inverse_of: :post
  
  has_many :subs,
  through: :postsubs,
  source: :subs
end

Reddit/app/models/postsub.rb
class Postsub < ApplicationRecord
  belongs_to :subs,
  foreign_key: :sub_id,
  class_name: :Sub
  
  belongs_to :posts,
    foreign_key: :post_id,
    class_name: :Post
end

Reddit/app/models/sub.rb
class Sub < ApplicationRecord
  belongs_to :moderators,
  foreign_key: :moderator_id,
  class_name: :User
  
  has_many :postsubs,
  foreign_key: :sub_id,
  class_name: :Postsub
  
  has_many :posts,
  through: :postsubs,
  source: :posts
end

Reddit/app/models/user.rb
class User < ApplicationRecord
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  
  has_many :mod_subs,
    foreign_key: :moderator_id,
    class_name: :Sub
    
  has_many :posts,
    foreign_key: :author_id,
    class_name: :Post
  
  attr_reader :password
  after_initialize :ensure_session_token
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && user.valid_password?(password)
    nil
  end
  
  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

Reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :logged_in?, :current_user
  
  def log_in!(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end
  
  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

Reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login
  def new
    @post = Post.new
  end
  
  def create 
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end
  
  def edit     
    @post = Post.find(params[:id])
  end
  
  def update 
    @post = current_user.posts.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end
  
  def show 
    @post = Post.find(params[:id])
  end
  
  def destroy 
    @post = Post.find(params[:id])
    if @post.author_id == current_user.id
      @post.destroy
    else
      flash[:errors] = ['You don\'t have right credentials to delete']
      redirect_to post_url(@post)
    end
  end
  
  private 
  
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

Reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    render :new
  end
  
  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user 
      log_in!(@user)
      redirect_to subs_url
    else 
      flash[:errors] = ["Incorrect Login Information or User Does Not Exist ;[ "]
      render :new
    end
  end
  
  def destroy
    logout!
    redirect_to new_session_url
  end
end

Reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find_by(id: params[:id])
  end

  def update
    @sub = current_user.mod_subs.find(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def edit
    @sub = current_user.mod_subs.find(params[:id])
  end

  def index
    @subs = Sub.all
  end

  def destroy
    @sub = current_user.mod_subs.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end
  
  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

Reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      redirect_to subs_url
    else 
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  private 
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

Reddit/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
  end
end

Reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= current_user.username %>
      
      <a href="<%=new_sub_url%>"> <button type="button" name="button">Make a New Sub</button></a>
      
      <form action= "<%= session_url %>" method="post">
        <%= auth_token %>
        <input type="hidden" name="_method" value="delete">
        
        <input type="submit" name="" value="Sign Out">
      </form>
    <% end %>
    
    <% if flash[:errors] %>
    <% flash[:errors].each do |err| %>
    <%= err %>
    <% end %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

Reddit/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

  <form class="" action="<%= post_url(@post) %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="_method" value="patch">
    
    <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
    </label>
    
    
    <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
    </label>
    
    <label>Content
    <input type="textarea" name="post[content]" value="<%= @post.content %>">
    </label>
    
    <% Sub.all.each do |sub| %>
    <label> <%= sub.title %>
      <input type="checkbox" 
        name="post[sub_ids][]" 
        value="<%= sub.id %>"
        <%= "checked" if @post.sub_ids.include?(sub.id) %> >
      </label>
    <% end %>
    
    
    <input type="submit" name="" value="Edit Post">
  </form>

Reddit/app/views/posts/new.html.erb
<h1>New Post</h1>

  <form class="" action="<%= posts_url %>" method="post">
    <%= auth_token %>
    
    <label>Title
    <input type="text" name="post[title]" value="">
    </label>
    
    
    <label>URL
    <input type="text" name="post[url]" value="">
    </label>
    
    <label>Content
    <input type="textarea" name="post[content]" value="">
    </label>
    
    <label>Subs: </label>
    
    <input type="hidden" name="post[sub_ids][]" value="">
    
    <% Sub.all.each do |sub| %>
    <label> <%= sub.title %>
      <input type="checkbox" 
        name="post[sub_ids][]" 
        value="<%= sub.id %>">
      </label>
    <% end %>
    
    
    <input type="submit" name="" value="Create Post">
  </form>
  

  
  
  <!--  Sub.all.each sub-->
  <!-- sub -->
  <!-- if selected sub.id -->

Reddit/app/views/posts/show.html.erb
<%= @post.author.username %>
<h3><%= @post.title %></h3>
<h5><%= @post.url %></h5>
<%= @post.content %>

<h5><a href="<%= edit_post_url(@post) %>">Edit Post</a></h5>

<form action= "<%= post_url(@post) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="delete">
  <input type="submit" name="" value="Delete Post">
  
</form>
  

Reddit/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

  <form action="<%= sub_url(@sub) %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <%= auth_token %>
    
    <label>Title
    <input type="text" name="sub[title]" value= "<%= @sub.title %>" >
    </label>
    
    
    <label>Description
    <input type="text" name="sub[description]" value= "<%= @sub.description %>" >
    </label>
    
    <input type="submit" name="" value="Edit Sub">
  </form>

Reddit/app/views/subs/index.html.erb
<ul>
<% @subs.each do |sub| %>
  <li>
    <a href="<%=sub_url(sub)%>">  <%= sub.title %> </a>
  </li>
<% end %>  
</ul>

Reddit/app/views/subs/new.html.erb
<h1>New Sub</h1>

  <form action="<%= subs_url %>" method="post">
    <%= auth_token %>
    
    <label>Title
    <input type="text" name="sub[title]" value="">
    </label>
    
    
    <label>Description
    <input type="text" name="sub[description]" value="">
    </label>
    
    <input type="submit" name="" value="Make New Sub">
  </form>

Reddit/app/views/subs/show.html.erb
<%= @sub.title %>
<%= @sub.description %>
<h5>Current Mod: <%= @sub.moderators.username %></h5> 
<a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>

<form action="<%=sub_url(@sub)%>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="delete">
  <input type="submit" name="" value="Remove Sub">
  
</form>

Reddit/app/views/users/new.html.erb
<h1>Sign Up</h1>

  <form class="" action="<%= users_url %>" method="post">
    <%= auth_token %>
    
    <label>Username
    <input type="text" name="user[username]" value="">
    </label>
    
    
    <label>Password
    <input type="text" name="user[password]" value="">
    </label>
    
    <input type="submit" name="" value="Sign Up">
  </form>